"""
Roadmap and recommendation models.
"""
import uuid
from datetime import datetime, timezone

from sqlalchemy import (
    Boolean, Column, DateTime, Float, ForeignKey,
    Index, Integer, String, Text,
)
from sqlalchemy.orm import relationship

from app.db.session import Base


def utcnow() -> datetime:
    return datetime.now(timezone.utc)


class CourseRecommendation(Base):
    """
    AI-generated course recommendation for a faculty member.
    Includes evidence from feedback, confidence score, and expected impact.
    """
    __tablename__ = "course_recommendations"
    __table_args__ = (
        Index("ix_recs_faculty_term", "faculty_profile_id", "term"),
        {"schema": "feedback"},
    )

    id: str = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    faculty_profile_id: str = Column(
        String(36),
        ForeignKey("feedback.faculty_profiles.id", ondelete="CASCADE"),
        nullable=False,
    )
    course_id: str | None = Column(
        String(36),
        ForeignKey("feedback.course_catalog.id", ondelete="SET NULL"),
        nullable=True,
    )
    term: str = Column(String(20), nullable=False)

    # Why this recommendation was generated
    target_dimension: str = Column(String(50), nullable=False)
    evidence_json: str = Column(Text, nullable=False)      # JSON: list of supporting feedback quotes/themes
    confidence_score: float = Column(Float, nullable=False)  # 0.0–1.0
    similarity_score: float | None = Column(Float, nullable=True)   # cosine similarity to course

    # LLM-generated justification
    justification_text: str | None = Column(Text, nullable=True)
    learning_outcomes_text: str | None = Column(Text, nullable=True)
    expected_impact_text: str | None = Column(Text, nullable=True)

    # Status tracking
    is_accepted: bool | None = Column(Boolean, nullable=True)       # None = not reviewed
    accepted_at: datetime | None = Column(DateTime(timezone=True), nullable=True)
    completed_at: datetime | None = Column(DateTime(timezone=True), nullable=True)

    created_at: datetime = Column(DateTime(timezone=True), default=utcnow, nullable=False)

    faculty = relationship("FacultyProfile", back_populates="recommendations")
    course = relationship("CourseCatalogEntry")


class FacultyRoadmap(Base):
    """
    Personalized 30/60/90-day improvement roadmap for a faculty member.
    Generated by the LLM pipeline based on scoring and recommendations.
    """
    __tablename__ = "faculty_roadmaps"
    __table_args__ = (
        Index("ix_roadmaps_faculty_term", "faculty_profile_id", "term"),
        {"schema": "feedback"},
    )

    id: str = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    faculty_profile_id: str = Column(
        String(36),
        ForeignKey("feedback.faculty_profiles.id", ondelete="CASCADE"),
        nullable=False,
    )
    faculty_id: str = Column(String(36), nullable=False)   # registry.users.id
    term: str = Column(String(20), nullable=False)

    # Band and composite at time of generation
    score_band: str = Column(String(20), nullable=False)
    composite_score: float = Column(Float, nullable=False)

    # LLM-generated plan content (JSON structure)
    day30_plan_json: str = Column(Text, nullable=False)    # {"goals": [...], "actions": [...]}
    day60_plan_json: str = Column(Text, nullable=False)
    day90_plan_json: str = Column(Text, nullable=False)

    # Overall narrative
    executive_summary: str | None = Column(Text, nullable=True)
    root_cause_analysis: str | None = Column(Text, nullable=True)

    # Progress tracking
    progress_percent: int = Column(Integer, default=0)
    last_reviewed_at: datetime | None = Column(DateTime(timezone=True), nullable=True)

    is_published: bool = Column(Boolean, default=False)     # Published to faculty portal
    published_at: datetime | None = Column(DateTime(timezone=True), nullable=True)

    created_at: datetime = Column(DateTime(timezone=True), default=utcnow, nullable=False)
    updated_at: datetime = Column(DateTime(timezone=True), default=utcnow, onupdate=utcnow, nullable=False)

    faculty_profile = relationship("FacultyProfile", back_populates="roadmaps", foreign_keys=[faculty_profile_id])
    faculty_user = relationship(
        "User",
        back_populates="roadmaps",
        primaryjoin="User.id == FacultyRoadmap.faculty_id",
        foreign_keys=[faculty_id],
    )
